global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'discord'  

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'http://discord-webhook-adapter:9094/discord'
    send_resolved: true

templates:
  - '/etc/alertmanager/alert-template.tmpl'
  
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']