services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    ports:
      - ${PROMETHEUS_PORT}:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerts.yml:/etc/prometheus/alerts.yml:ro
    restart: always
    depends_on:
      - cadvisor
      - alertmanager

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0-security-01
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
    - ./grafana-data:/var/lib/grafana  
    restart: always
    depends_on:
      - prometheus

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./alert-template.tmpl:/etc/alertmanager/alert-template.tmpl:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: always

  discord-webhook-adapter:
    container_name: discord-webhook-adapter
    image: benjojo/alertmanager-discord:latest
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    restart: always  