apiVersion: v1
kind: Service
metadata:
  name: {{ include "aspnetapp.fullname" . }}-nodeport
  labels:
    {{- include "aspnetapp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.nodePort.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aspnetapp.selectorLabels" . | nindent 4 }}
