global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'discord'  

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'https://discord.com/api/webhooks/1379390436543823982/UWLO83zSjOl54aQ1PLW7i1dnM2nYf5Gq5AvJExG2GLAUuWBB3EnYaHlnjASx6dkHRltZ'
    send_resolved: true
    http_config: {}
    max_alerts: 0

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']